-- 図書館の業務スキーマ用。空の専用スキーマで初回だけ実行する。
-- 既存の表・データは削除しない。DBeaver等でスクリプト実行する。

CREATE TABLE BOOK (
    BOOK_ID VARCHAR2(36 CHAR) NOT NULL,
    TITLE VARCHAR2(200 CHAR) NOT NULL,
    AUTHOR_DISPLAY_NAME VARCHAR2(200 CHAR) NOT NULL,
    CATEGORY VARCHAR2(50 CHAR) NOT NULL,
    CONSTRAINT PK_BOOK PRIMARY KEY (BOOK_ID)
);
CREATE TABLE BOOK_COPY (
    BOOK_COPY_ID VARCHAR2(36 CHAR) NOT NULL,
    BOOK_ID VARCHAR2(36 CHAR) NOT NULL,
    ACCESSION_NUMBER VARCHAR2(30 CHAR) NOT NULL,
    SHELF_LOCATION VARCHAR2(50 CHAR),
    CONSTRAINT PK_BOOK_COPY PRIMARY KEY (BOOK_COPY_ID),
    CONSTRAINT FK_COPY_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID),
    CONSTRAINT UQ_COPY_ACCESSION UNIQUE (ACCESSION_NUMBER)
);
CREATE TABLE MEMBER (
    MEMBER_ID VARCHAR2(36 CHAR) NOT NULL,
    MEMBER_NUMBER VARCHAR2(30 CHAR) NOT NULL,
    DISPLAY_NAME VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_ID),
    CONSTRAINT UQ_MEMBER_NUMBER UNIQUE (MEMBER_NUMBER)
);
CREATE TABLE APP_USER (
    USER_ID VARCHAR2(36 CHAR) NOT NULL,
    LOGIN_NAME VARCHAR2(100 CHAR) NOT NULL,
    PASSWORD_HASH VARCHAR2(512 CHAR),
    ROLE_CODE VARCHAR2(10 CHAR) NOT NULL,
    MEMBER_ID VARCHAR2(36 CHAR),
    CONSTRAINT PK_APP_USER PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USER_LOGIN UNIQUE (LOGIN_NAME),
    CONSTRAINT UQ_USER_MEMBER UNIQUE (MEMBER_ID),
    CONSTRAINT FK_USER_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT CK_USER_LOGIN CHECK (REGEXP_LIKE(LOGIN_NAME, '^[a-z0-9._-]+$', 'c')),
    CONSTRAINT CK_USER_ROLE CHECK (ROLE_CODE IN ('Librarian', 'Member')),
    CONSTRAINT CK_USER_MEMBER CHECK (
        (ROLE_CODE = 'Member' AND MEMBER_ID IS NOT NULL)
        OR (ROLE_CODE = 'Librarian' AND MEMBER_ID IS NULL))
);
CREATE TABLE LOAN (
    LOAN_ID VARCHAR2(36 CHAR) NOT NULL,
    BOOK_COPY_ID VARCHAR2(36 CHAR) NOT NULL,
    MEMBER_ID VARCHAR2(36 CHAR) NOT NULL,
    BORROWED_ON DATE NOT NULL,
    DUE_DATE DATE NOT NULL,
    BORROWED_AT TIMESTAMP(6) NOT NULL,
    BORROWED_BY VARCHAR2(36 CHAR) NOT NULL,
    RETURNED_AT TIMESTAMP(6),
    RETURNED_BY VARCHAR2(36 CHAR),
    CONSTRAINT PK_LOAN PRIMARY KEY (LOAN_ID),
    CONSTRAINT FK_LOAN_COPY FOREIGN KEY (BOOK_COPY_ID) REFERENCES BOOK_COPY (BOOK_COPY_ID),
    CONSTRAINT FK_LOAN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID),
    CONSTRAINT FK_LOAN_BORROWER_USER FOREIGN KEY (BORROWED_BY) REFERENCES APP_USER (USER_ID),
    CONSTRAINT FK_LOAN_RETURNER_USER FOREIGN KEY (RETURNED_BY) REFERENCES APP_USER (USER_ID),
    CONSTRAINT CK_LOAN_DAY CHECK (BORROWED_ON = TRUNC(BORROWED_ON)),
    CONSTRAINT CK_LOAN_DUE CHECK (DUE_DATE = BORROWED_ON + 14),
    CONSTRAINT CK_LOAN_RETURN_PAIR CHECK (
        (RETURNED_AT IS NULL AND RETURNED_BY IS NULL)
        OR (RETURNED_AT IS NOT NULL AND RETURNED_BY IS NOT NULL)),
    CONSTRAINT CK_LOAN_RETURN_TIME CHECK (RETURNED_AT IS NULL OR RETURNED_AT >= BORROWED_AT)
);
CREATE UNIQUE INDEX UQ_LOAN_OPEN_COPY ON LOAN
    (CASE WHEN RETURNED_AT IS NULL THEN BOOK_COPY_ID ELSE NULL END);
CREATE INDEX IX_COPY_BOOK ON BOOK_COPY (BOOK_ID);
CREATE INDEX IX_LOAN_COPY_RETURN ON LOAN (BOOK_COPY_ID, RETURNED_AT);
CREATE INDEX IX_LOAN_MEMBER_RETURN ON LOAN (MEMBER_ID, RETURNED_AT);
CREATE INDEX IX_LOAN_RETURN_DUE ON LOAN (RETURNED_AT, DUE_DATE);
CREATE INDEX IX_LOAN_BORROWED_BY ON LOAN (BORROWED_BY);
CREATE INDEX IX_LOAN_RETURNED_BY ON LOAN (RETURNED_BY);

COMMENT ON TABLE BOOK IS '書籍情報';
COMMENT ON COLUMN BOOK.BOOK_ID IS '書籍ID';
COMMENT ON COLUMN BOOK.TITLE IS '書名';
COMMENT ON COLUMN BOOK.AUTHOR_DISPLAY_NAME IS '著者表示名';
COMMENT ON COLUMN BOOK.CATEGORY IS 'ジャンル';
COMMENT ON TABLE BOOK_COPY IS '所蔵する実物の一冊';
COMMENT ON COLUMN BOOK_COPY.BOOK_COPY_ID IS '蔵書ID';
COMMENT ON COLUMN BOOK_COPY.BOOK_ID IS '書籍ID';
COMMENT ON COLUMN BOOK_COPY.ACCESSION_NUMBER IS '蔵書番号';
COMMENT ON COLUMN BOOK_COPY.SHELF_LOCATION IS '棚の場所 未設定はNULL';
COMMENT ON TABLE MEMBER IS '図書館の利用者';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '利用者ID';
COMMENT ON COLUMN MEMBER.MEMBER_NUMBER IS '利用者番号';
COMMENT ON COLUMN MEMBER.DISPLAY_NAME IS '利用者表示名';
COMMENT ON TABLE APP_USER IS 'アカウントと操作者';
COMMENT ON COLUMN APP_USER.USER_ID IS 'アカウントID';
COMMENT ON COLUMN APP_USER.LOGIN_NAME IS 'ログイン名';
COMMENT ON COLUMN APP_USER.PASSWORD_HASH IS 'パスワードハッシュ NULLはログイン不可';
COMMENT ON COLUMN APP_USER.ROLE_CODE IS 'LibrarianまたはMember';
COMMENT ON COLUMN APP_USER.MEMBER_ID IS 'Memberロールの業務利用者ID';
COMMENT ON TABLE LOAN IS '実物の一冊を貸し出した一回の記録';
COMMENT ON COLUMN LOAN.LOAN_ID IS '貸出ID';
COMMENT ON COLUMN LOAN.BOOK_COPY_ID IS '蔵書ID';
COMMENT ON COLUMN LOAN.MEMBER_ID IS '借り手の利用者ID';
COMMENT ON COLUMN LOAN.BORROWED_ON IS '貸出日 日本時間の暦日';
COMMENT ON COLUMN LOAN.DUE_DATE IS '返却期限 貸出日から14日後';
COMMENT ON COLUMN LOAN.BORROWED_AT IS '貸出登録時刻 UTC';
COMMENT ON COLUMN LOAN.BORROWED_BY IS '貸出登録者のアカウントID';
COMMENT ON COLUMN LOAN.RETURNED_AT IS '返却登録時刻 UTC 未返却はNULL';
COMMENT ON COLUMN LOAN.RETURNED_BY IS '返却登録者のアカウントID';
